# Generated by Django 4.0.3 on 2022-03-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0006_image_image_location_alter_image_image_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image_name']},
        ),
    ]
